#!/bin/bash

ls pos | grep .bmp | awk '{print $0 " 1 0 0 24 24"}' > pos/pos.txt
NUMPOS=`cat pos/pos.txt|wc -l`

ls neg | grep .bmp > neg/neg.txt
NUMNEG=`cat neg/neg.txt|wc -l`

opencv_createsamples \
	-info pos/pos.txt \
	-vec pos.vec \
	-bg neg/neg.txt \
	-num $NUMPOS \
	-w 24 -h 24 \
	|| exit

echo "======================"

opencv_traincascade \
	-data xml \
	-vec pos.vec \
	-bg neg/neg.txt \
	-featureType LBP \
	-numPos $NUMPOS \
	-numNeg $NUMNEG \
	-numStages 20 \
	-w 24 -h 24 \
	|| exit

echo "======================"

cp xml/cascade.xml /output/
